FROM node:12.18.4-alpine3.9

RUN mkdir -p /app
WORKDIR /app
COPY . /app/

RUN npm i -g npm 
RUN npm install
RUN npm install --global cross-env
# RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "dev" ]