FROM node:12.18.4-alpine3.9

ENV ROUTER_BASE="/app/services"
ENV PUBLIC_PATH="/_nuxt/"
ENV GENERATE_DIR="./dist/"
ENV NUXT_TELEMETRY_DISABLED=1
#proxy
# v1
ENV PROXY_PATH="/api/services/"
ENV PROXY_TARGET="/"
# axios
ENV BASE_URL="/api/services"
#socket
ENV SOCKET_SERVER="/"
ENV SOCKET_PATH="/api/services/socket.io"

RUN mkdir -p /app
WORKDIR /app
# COPY . /app/

COPY package*.json ./
# RUN npm i -g npm 
RUN npm install
COPY . .
RUN npm install --global cross-env
RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]