FROM node:12.18.4-alpine3.9 as api
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app/
COPY package-lock.json /app/
RUN npm install
# Bundle app source
COPY . /app/
EXPOSE 4000
CMD [ "npm", "start" ]